### ISSUE TITLE
bleCombo.print does not work properly

### ISSUE THREAD

**Issue by bakharew** [Cemu0/ESP32-BLE-Combo#1]
Hi, 

I've tried your library, and it does not have any connectivity issues on iOS like others trying to combine keyboard and mouse. 

However, I encountered strange issues when using bleCombo.print. Very often it prints incomplete text and sometimes holds the last letter key indefinitely. Any tips to fix that?

**Comment by bakharew** [comment]
https://user-images.githubusercontent.com/26136354/192154122-4ffe3836-94e4-42af-b617-204b053ceb28.MP4

**Comment by bakharew** [comment]
I spawned some delays when keys pressing/releasing and it helped

**Comment by Cemu0** [comment]
Yeah, look like it has some problem with delay time when using ios devices, It could be because of the delay time (original 7ms), changes with `setDelay()`. Or because I was adding the ` taskYIELD(); ` into the delay_ms function, so you can try removing this too. 
```
void BleCombo::delay_ms(uint64_t ms) {
  uint64_t m = esp_timer_get_time();
  if(ms){
    uint64_t e = (m + (ms * 1000));
    if(m > e){ //overflow
        while(esp_timer_get_time() > e) { taskYIELD();}
    }
    while(esp_timer_get_time() < e) {taskYIELD();}
  }
}
```

**Comment by Cemu0** [comment]
Change _delay_ms = 7 seem to fix the problem. Thank you!
